[package]
name = "truffle-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
truffle-sim = { git = "https://github.com/mookums/truffle.git" }
wasm-bindgen = "0.2.100"

