[package]
name = "truffle-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
serde-wasm-bindgen = "0.6.5"
truffle-sim = { git = "https://github.com/mookums/truffle.git", features = [ "serde" ] }
wasm-bindgen = "0.2.100"

